url: "https://winterhawk.photography"
title: WinterHawk Photography
description: WinterHawk Photography primarily focuses on nature photography, including landscapes, animals, lakes, parks, zoos, and other elements of the natural world.

sass:
    style: compressed

plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from

# Output options (more information on Jekyll's site)
encoding: UTF-8
timezone: America/New_York
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 5
kramdown:
  input: GFM

#SEO configuration

social:
  name: WinterHawk Photography
  links:
    - https://instagram.com/winterhawkphotography
    - https://www.facebook.com/winterhawkphotography

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
